### ISSUE TITLE
install.txt

### ISSUE THREAD

**Issue by tuxmuck** [PepeCyB/keulkulator#1]
Eine "install.txt" sollte noch mit rein -

Gruss
miko ;-)

**Comment by PepeCyB** [comment]
Die kommt noch. Bisher gibt es noch nix zu installieren.

Habe inzwischen aber schon "Platzhalter" unter docs/build-instructions eingefügt… "install" folgt.

**Comment by PepeCyB** [comment]
Datei (vorerst mit Verweis auf README.md) erstellt.
